- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/ScrollBarRepresentation.java
> scrollbar: added "active" flag to prevent UI updates from causing PV

- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/DisplayEditor.java
- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/util/Rubberband.java
> Editor: Fix rubberband offset when view of display is scrolled

- org.csstudio.display.builder.model.test/src/org/csstudio/display/builder/model/macros/MacrosUnitTest.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/macros/MacroHandler.java
"$(X=x)" becomes "x" if macro X is not defined
> MacroHandler: added default value ($(X=x)) and tests

- org.csstudio.display.builder.model.test/src/org/csstudio/display/builder/model/macros/MacrosUnitTest.java
- org.csstudio.display.builder.model/examples/embedded/structure_embedded.bob
- org.csstudio.display.builder.model/examples/embedded/template.bob
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/Messages.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/macros/MacroHandler.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/messages.properties
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/EmbeddedDisplayWidget.java
- org.csstudio.display.builder.runtime/src/org/csstudio/display/builder/runtime/internal/EmbeddedDisplayRuntime.java
Embedded widget has group_name property
> Embedded group

- org.csstudio.display.builder.model/examples/scripts/python/update_pv_name.py
- org.csstudio.display.builder.model/examples/scripts/python/update_text.py
- org.csstudio.display.builder.model/examples/scripts/python/update_x.py
- org.csstudio.display.builder.model/examples/scripts/update_pv_name.py
- org.csstudio.display.builder.model/examples/scripts/update_text.py
- org.csstudio.display.builder.model/examples/scripts/update_x.py
- org.csstudio.display.builder.model/examples/scripts_python-vs-jython.bob
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/properties/ScriptInfo.java
- org.csstudio.display.builder.runtime.test/examples/updateText_python.py
- org.csstudio.display.builder.runtime.test/src/org/csstudio/display/builder/runtime/test/PythonGatewaySupportTest.java
- org.csstudio.display.builder.runtime/scripts/connect2j.py
- org.csstudio.display.builder.runtime/scripts/setup.py
- org.csstudio.display.builder.runtime/scripts/test-script.py
- org.csstudio.display.builder.runtime/src/org/csstudio/display/builder/runtime/script/internal/JythonScriptSupport.java
- org.csstudio.display.builder.runtime/src/org/csstudio/display/builder/runtime/script/internal/PythonGatewaySupport.java
- org.csstudio.display.builder.runtime/src/org/csstudio/display/builder/runtime/script/internal/PythonScriptSupport.java
scriptContext is uniform between Python and Jython
> Python script support

- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/tracker/TrackerSnapConstraint.java
> TrackerSnapConstraint: better guide-line size

- org.csstudio.display.builder.model/examples/embedded/a.bob
- org.csstudio.display.builder.model/examples/embedded/b.bob
- org.csstudio.display.builder.model/examples/embedded/structure_embedded.bob
- org.csstudio.display.builder.model/examples/embedded/template.bob
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/DisplayModel.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/Widget.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/persist/ModelLoader.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/util/ModelResourceUtil.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/util/NamedDaemonPool.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/EmbeddedDisplayWidget.java
- org.csstudio.display.builder.rcp/src/org/csstudio/display/builder/rcp/RuntimeApplication.java
- org.csstudio.display.builder.rcp/src/org/csstudio/display/builder/rcp/RuntimeViewPart.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/JFXRepresentation.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/EmbeddedDisplayRepresentation.java
- org.csstudio.display.builder.representation.swt/src/org/csstudio/display/builder/representation/swt/SWTRepresentation.java
- org.csstudio.display.builder.representation.swt/src/org/csstudio/display/builder/representation/swt/widgets/EmbeddedDisplayRepresentation.java
- org.csstudio.display.builder.representation/src/org/csstudio/display/builder/representation/EmbeddedDisplayRepresentationUtil.java
- org.csstudio.display.builder.representation/src/org/csstudio/display/builder/representation/ToolkitRepresentation.java
- org.csstudio.display.builder.runtime.test/src/org/csstudio/display/builder/runtime/test/JythonScriptTest.java
- org.csstudio.display.builder.runtime.test/src/org/csstudio/display/builder/runtime/test/PythonScriptTest.java
- org.csstudio.display.builder.runtime.test/src/org/csstudio/display/builder/runtime/test/RulesJythonScriptTest.java
- org.csstudio.display.builder.runtime.test/src/org/csstudio/display/builder/runtime/test/RuntimeDemoJavaFX.java
- org.csstudio.display.builder.runtime.test/src/org/csstudio/display/builder/runtime/test/RuntimeDemoSWT.java
- org.csstudio.display.builder.runtime/src/org/csstudio/display/builder/runtime/ActionUtil.java
- org.csstudio.display.builder.runtime/src/org/csstudio/display/builder/runtime/RuntimeUtil.java
- org.csstudio.display.builder.runtime/src/org/csstudio/display/builder/runtime/internal/EmbeddedDisplayRuntime.java
- org.csstudio.display.builder.runtime/src/org/csstudio/display/builder/runtime/script/ScriptUtil.java
Fixes #105, allows seeing the embedded content in the editor.
> Embedded 105

- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/PropertyPanelSection.java
- org.csstudio.display.builder.model/examples/01_main.bob
- org.csstudio.display.builder.model/examples/06_runtime.bob
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/Messages.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/RuntimeWidgetProperty.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/messages.properties
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/properties/CommonWidgetProperties.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/PVWidget.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/VisibleWidget.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/opibuilder.css
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/JFXBaseRepresentation.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/TooltipSupport.java
> Tooltip 103

- org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/DisplayEditorPart.java
- org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/EditEmbeddedDisplayAction.java
- org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/Messages.java
- org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/OpenDisplayInEditor.java
- org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/messages.properties
- org.csstudio.display.builder.rcp/src/org/csstudio/display/builder/rcp/RuntimeViewPart.java
- org.csstudio.display.builder.rcp/src/org/csstudio/display/builder/rcp/run/ContextMenuSupport.java
https://github.com/ControlSystemStudio/cs-studio/issues/1908
> Edit embedded

- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/RulesDialog.java
- org.csstudio.display.builder.model.test/src/org/csstudio/display/builder/model/properties/RuleToScript_ReplaceLogicalOpsTest.java
- org.csstudio.display.builder.model.test/src/org/csstudio/display/builder/model/properties/RulesTest.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/properties/RuleInfo.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/properties/RuleToScript.java
- org.csstudio.display.builder.runtime/src/org/csstudio/display/builder/runtime/script/internal/RuntimeScriptHandler.java
> Rule adjust

- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/tracker/SelectedWidgetUITracker.java
- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/tracker/TrackerGridConstraint.java
- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/util/WidgetTransfer.java
- org.csstudio.display.builder.model.rcp/META-INF/MANIFEST.MF
- org.csstudio.display.builder.model.rcp/src/org/csstudio/display/builder/model/util/WorkspaceResourceHelperImpl.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/persist/ModelReader.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/util/ModelResourceUtil.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/util/WorkspaceResourceHelper.java
Handles #153 :
* path to picture or embedded display made relative, and handling workspace
* Checking image or embedded display detail off the UI thread
* When creating multiple widgets, they're stacked vertically instead of mostly being on top of each other
* Dialogs that prompt what to do with dropped content positioned relative to mouse, not appearing on different monitor
* URL patch for Linux
* Log messages show exception trace
> Dnd updates

- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/RulesDialog.java
- org.csstudio.display.builder.model.test/src/org/csstudio/display/builder/model/WidgetPropertiesUnitTest.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/Widget.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/properties/RuleInfo.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/properties/RulesWidgetProperty.java
Fixes rules assigned to path-based properties like XYPlot's "yaxes[1].maximum"
> Rules for path props

- databrowser3/databrowser-plugins/pom.xml
- org.csstudio.display.builder.model/examples/05_actions.bob
- org.csstudio.display.builder.model/examples/import-test/action_buttons.bob
- org.csstudio.display.builder.model/examples/import-test/action_buttons.opi
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/persist/XMLTags.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/properties/ActionInfo.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/properties/ActionsWidgetProperty.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/properties/ExecuteCommandActionInfo.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/ActionsDialog.java
- org.csstudio.display.builder.runtime.test/examples/cmd_error.sh
- org.csstudio.display.builder.runtime.test/examples/cmd_long.sh
- org.csstudio.display.builder.runtime.test/examples/cmd_short.sh
- org.csstudio.display.builder.runtime.test/src/org/csstudio/display/builder/runtime/test/CommandExecutorTest.java
- org.csstudio.display.builder.runtime/src/org/csstudio/display/builder/runtime/ActionUtil.java
- org.csstudio.display.builder.runtime/src/org/csstudio/display/builder/runtime/CommandExecutor.java
> Ext commands

- databrowser3/databrowser-plugins/org.csstudio.trends.databrowser3/src/org/csstudio/trends/databrowser3/propsheet/ChangeAxisConfigCommand.java
- databrowser3/databrowser-plugins/org.csstudio.trends.databrowser3/src/org/csstudio/trends/databrowser3/ui/ControllerBase.java
- databrowser3/databrowser-plugins/org.csstudio.trends.databrowser3/src/org/csstudio/trends/databrowser3/ui/ModelBasedPlot.java
- org.csstudio.javafx.rtplot.test/src/org/csstudio/javafx/rtplot/BasicPlotDemo.java
- org.csstudio.javafx.rtplot.test/src/org/csstudio/javafx/rtplot/ValuePlotDemo.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/Axis.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/RTPlot.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/RTPlotListener.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/AxisPart.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/Plot.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/PlotProcessor.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/ToolbarHandler.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/undo/ChangeAxisRanges.java
> 205 auto de autoscale

- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/BaseGaugeWidget.java
**NOTE:** cs-[studio-thirdparty#32](https://github.com/ControlSystemStudio/cs-studio-thirdparty/pull/32) must be merged first.
> Added unit_from_pv property.

- org.csstudio.display.builder.model/examples/01_main.bob
- org.csstudio.display.builder.model/examples/monitors_gauge.bob
- org.csstudio.display.builder.model/examples/monitors_meter.bob
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/MeterRepresentation.java
Added examples for meters and gauges.
Fixed NPE loading GAUGE and 3/4 gauges.
> Example and NPE fix

- org.csstudio.javafx.rtplot.test/src/org/csstudio/javafx/rtplot/LinearTicksTest.java
- org.csstudio.javafx.rtplot.test/src/org/csstudio/javafx/rtplot/LogTicksTest.java
- org.csstudio.javafx.rtplot.test/src/org/csstudio/javafx/rtplot/TicksTestBase.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/AxisPart.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/HorizontalNumericAxis.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/LinearTicks.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/LogTicks.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/MajorTick.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/MinorTick.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/Plot.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/Ticks.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/TimeAxis.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/TimeTicks.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/YAxisImpl.java
Rework of the axis tick determination.
Fixes numerous issue with axis labels overlapping, being totally absent, especially for the log axis.
Fixes https://github.com/ControlSystemStudio/cs-studio/issues/1402 for the JavaFX RTPlot
> Axis ticks

- org.csstudio.display.builder.model/examples/controls_knob.bob
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/Messages.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/messages.properties
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/KnobWidget.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/KnobRepresentation.java
- Example completed.
- drag_disabled property added.
- Min and max correctly updated.
**Note:** [#46](https://github.com/ControlSystemStudio/cs-studio-thirdparty/pull/46) must be merged first. The gauges library must then refreshed in Eclipse.
> Fef fixes for KnobWidget

- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/opieditor.css
- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/PropertyPanelSection.java
Added fillers around variable properties.
> CSSTUDIO 165 variable properties group

- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/EmbeddedDisplayRepresentation.java
> Disposing the content of an embedded display.

- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SymbolRepresentation.java
- Added missing binding between image view's image and the current image index.
> Issue #299

- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/WidgetColorPopOverController.java
- On spinner's focus lost, spinner value is updated (spinners behave a bit oddly).
- On spinner's focus gained, the value is selected speeding up text entry.
> Color pop-over updated to improve interaction with spinners.

- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/ScriptsDialog.java
Changes to Scripts dialog:
- if no script is selected, only the Add Script button is enabled;
- when a new script is added it is selected, and its name is automatically edited to quickly set it;
- when a script is selected, and no PV is selected, only the Add PV button is enabled;
- when a new PV is added it is selected, and the PV name is automatically edited to quickly set it;
- for both tables, if the editor loses focus, the editing is cancelled;
- when a new script and/or PV is added (and edited), the Add PV button takes the focus, so pressing the SPACE bar will allow for quick addition of new PVs.
> First set of changes to Scripts dialog:

- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/ScriptsDialog.java
- org.csstudio.javafx/META-INF/MANIFEST.MF
- org.csstudio.javafx/src/org/csstudio/javafx/LineNumberTableCellFactory.java
- org.csstudio.javafx/src/org/csstudio/javafx/SyntaxHighlightedMultiLineInputDialog.java
- org.csstudio.javafx/src/org/csstudio/javafx/richtext/JavaHighlighter.java
- org.csstudio.javafx/src/org/csstudio/javafx/richtext/JavaScriptHighlighter.java
- org.csstudio.javafx/src/org/csstudio/javafx/richtext/LanguageHighlighter.java
- org.csstudio.javafx/src/org/csstudio/javafx/richtext/PythonHighlighter.java
- org.csstudio.javafx/src/org/csstudio/javafx/richtext/java-keywords.css
- org.csstudio.javafx/src/org/csstudio/javafx/richtext/javascript-keywords.css
- org.csstudio.javafx/src/org/csstudio/javafx/richtext/python-keywords.css
I was asked for even further improvements (like a button in the scripts editor to import as comments the current PV list), but I will not to more than what done in this last pull request.
After that I'll try to improve the Rules dialog in way similar to what done to the Scripts one till now.
> 286 dialogs issues: last changes to Scripts dialog.

- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/JFXStageRepresentation.java
Tested on MacOS X and CentOS 7.3.
> CSSTUDIO-596: standalone windows badly sized.

- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/JFXUtil.java
Tested with the first 10 pages of Display Builder examples:
- Color instances are now 10-20% of the uncached version;
- Fonts instances are now 30-50% of the uncached version;
- Methods where cache is used are at least twice fast then before.
All caches are weak, so when the WidgetColor/WidgetFont keys lose their strong references, the corresponding cached elements could be removed by GC.
> CSSTUDIO-600: using weak caches for colors and fonts

- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/macros/Macros.java
Closes #361 
I think it is perfectly fine to impose no '-' as first character.
> CSSTUDIO-614: Updated MACRO_NAME_PATTERN to accept also dashes (not as first char).

- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/SpinnerWidget.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SpinnerRepresentation.java
> CSSTUDIO-617: show unit in spinner

- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/PictureRepresentation.java
It requires the new maven-osgi-bundles ([#65](https://github.com/ControlSystemStudio/maven-osgi-bundles/pull/65)) to be merged.
> Temporary fix for bad positioning if scaled to adapt.

- org.csstudio.display.builder.editor.rcp/pom.xml
Added antrun plugin in pom.xml to execute "ant -f javadoc.xml clean all" from Maven.
This partially solves #385.
> 385 javadoc for widgets

- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SymbolRepresentation.java
Fixed a problem when a bad symbol index is used for widgets without an assigned PV.
> CSSTUDIO-721: symbol updates

- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/ActionsPropertyBinding.java
- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/ColorMapPropertyBinding.java
- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/MacrosPropertyBinding.java
- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/PointsPropertyBinding.java
- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/PropertyPanelSection.java
- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/RulesDialog.java
- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/RulesPropertyBinding.java
- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/ScriptsPropertyBinding.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/ActionsDialog.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/ColorMapDialog.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/JFXStageRepresentation.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/MacrosDialog.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/PointsDialog.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/ScriptsDialog.java
- org.csstudio.javafx/src/org/csstudio/javafx/DialogHelper.java
- org.csstudio.javafx/src/org/csstudio/javafx/MultiLineInputDialog.java
- org.csstudio.javafx/src/org/csstudio/javafx/PreferencesHelper.java
- org.csstudio.javafx/src/org/csstudio/javafx/SyntaxHighlightedMultiLineInputDialog.java
- Some dialogs still disappeared clicking on the main application window.
- More dialogs will save/restore their position and size.
> Fixing some issues with dialogs.

- org.csstudio.display.builder.editor.rcp/javadoc.xml
This will complete #413 and #414.
> Added FormatOption and FormatOptionHandler to the Script API help.

- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SymbolRepresentation.java
- Fixed initial image (not SVG) not displayed.
- Improved image size computation speed.
> Initial image (not SVG) not displayed.

- org.csstudio.display.builder.editor.rcp/javadoc.xml
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/DisplayModel.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/Widget.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/WidgetProperty.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/macros/Macros.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/properties/FormatOption.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/util/FormatOptionHandler.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/SymbolWidget.java
- org.csstudio.display.builder.runtime/src/org/csstudio/display/builder/runtime/pv/RuntimePV.java
- org.csstudio.display.builder.runtime/src/org/csstudio/display/builder/runtime/script/PVUtil.java
- org.csstudio.display.builder.runtime/src/org/csstudio/display/builder/runtime/script/ValueUtil.java
Fixed all javadoc errors and warnings not related to references or symbols not found.
> DB API javadoc fixes

- org.csstudio.display.builder.rcp/META-INF/MANIFEST.MF
- org.csstudio.display.builder.runtime.test/META-INF/MANIFEST.MF
- org.csstudio.display.builder.runtime/META-INF/MANIFEST.MF
[#74](https://github.com/ControlSystemStudio/maven-osgi-bundles/pull/74) is required first.
> Updated references to Jython ver. 2.7.1.

- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/BaseGaugeRepresentation.java
Added missing valueChange call at listeners registration time.
> CSSTUDIO-863: gauges and meters not showing initial PV value.

- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/Widget.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/KnobWidget.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/ScaledSliderWidget.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/ScrollBarWidget.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/SpinnerWidget.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/TableWidget.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/TextEntryWidget.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/TextUpdateWidget.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/plots/ImageWidget.java
- org.csstudio.display.builder.rcp/src/org/csstudio/display/builder/rcp/RuntimeViewPart.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/ScaledSliderRepresentation.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/ScrollBarRepresentation.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SpinnerRepresentation.java
> CSSTUDIO-859: right click on spinner and scrollbar buttons, knob and scaled slider thumb lane.

- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/ByteMonitorRepresentation.java
> ByteMonitor labels aligment.

- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/BaseGaugeRepresentation.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/JFXBaseRepresentation.java
Fixed also some NPEs at runtime.
> Linear Meter Title disappears

- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/Messages.java
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/messages.properties
- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/TankWidget.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/TankRepresentation.java
- org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/RTTank.java
As requested by my stakeholders:
- Scale can be hidden.
- 3D effect less prominent.
> Tank widget update

- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/tree/WidgetTreeCell.java
Overridden cancelEdit to call updateItem.
> ESC hides icon in overview tree.

- org.csstudio.display.builder.model/examples/template_and_script/many_slidebuttons.bob
- org.csstudio.display.builder.model/examples/template_and_script/many_thumbwheels.bob
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/BaseGaugeRepresentation.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/BaseKnobRepresentation.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/LinearMeterRepresentation.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/MeterRepresentation.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SlideButtonRepresentation.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/ThumbWheelRepresentation.java
Updated Thumbwheel and SlideButton (big advantage on this one).
Knobs, Meters and Gauges don't have advantages on using unmanaged widgets (they are inefficient by themselves. I've already plans to redesign them in a different way). Instead I've improved their `updateLImits()` methods.
> Unmanaged widgets #1

- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/CheckBoxRepresentation.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SlideButtonRepresentation.java
Fixed also autosize not invoked in SlideButton for label or font change.
> Implemented autosize for Checkbox using heuristics.

- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/ScrollBarRepresentation.java
- org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SpinnerRepresentation.java
The previous fixes (commits 39df057fee968116bbbcf445541225ab7c03de60 and b4bfc9e047f6880c237180cdac1c9ae6d4f4cc0a) didn't solve the original issue opened by our users. Moreover the same problem is suffered by the ScrollBar widget
The following cases still exists (based on Spinner but equally working for ScrollBar):
- Press left mouse button on the spinner's increment button and keep it pressed: the spinner starts spinning.
- Drag outside the spinner boundary: the spinner continues to spin.
- Press also the right mouse button and keep it pressed: the context menu appears while the spinner continues spinning.
Until both mouse buttons are released, the spinner continues spinning. Context menu items can be selected too.
- Press left mouse button on the spinner's increment button and keep it …
> Spinner and ScrollBar continue to increment/decrement when context menu is open

- org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/DisplayEditorPart.java
- org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/OutlinePage.java
Paste action is enabled only if clipboard contain string that is parsable.
> Improved Paste action enabling evaluation.

- org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/MacroizedWidgetProperty.java
https://github.com/kasemir/org.csstudio.display.builder/issues/530
> Warn about unresolved macros

- org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/DisplayEditorPart.java
- org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/Messages.java
- org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/messages.properties
- org.csstudio.display.builder.model.rcp/src/org/csstudio/display/builder/model/util/WorkspaceResourceHelperImpl.java
- org.csstudio.display.builder.rcp/src/org/csstudio/display/builder/rcp/Messages.java
- org.csstudio.display.builder.rcp/src/org/csstudio/display/builder/rcp/RuntimeViewPart.java
- org.csstudio.display.builder.rcp/src/org/csstudio/display/builder/rcp/messages.properties
Some of the tests performed by previous PR (#541) are not working if a `.bob` file is open from a git-mounted project.
Moreover user's messages are now correctly localised.
> CSSTUDIO-945 rollback

- org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/util/WidgetTransfer.java
It uses partial knowledge (the "databrowser" type) and introspection to add the DataBrowser widget.
> Added D&D of .plt files in DB editor.
