org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/ScaledSliderRepresentation.java

The slider displayed oddly in both CSS and the standalone demos and caused errors with other widgets in the standalone demos when limits_from_pv was true and the PV had no limits.

scaled slider: clean up limits_from_pv to allow for NaN limits

---

org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/DisplayEditor.java
org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/tracker/SelectedWidgetUITracker.java
org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/tracker/TrackerGridConstraint.java
org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/tracker/TrackerSnapConstraint.java
org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/DisplayModel.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/JFXRepresentation.java
org.csstudio.display.builder.representation.swt/src/org/csstudio/display/builder/representation/swt/SWTRepresentation.java
org.csstudio.display.builder.representation/src/org/csstudio/display/builder/representation/ToolkitRepresentation.java

The grid display and the editor UI hint for the display size had to add getters and setters for all the grid and display size information. In principle, that information is in the DisplayModel, but the model was not accessible in the JFXRepresentation (because private in base class) nor the Tracker*Contrains (not passed in).
By changing to a 'protected model' in the TollkitRepresentation and by updating the model in the Tracker, one-caller getters and setters could be replaced by plain model property listeners.

Representation tracks model

---

org.csstudio.display.builder.feature/feature.xml
org.csstudio.javafx/META-INF/MANIFEST.MF
org.csstudio.javafx/src/org/csstudio/javafx/Activator.java

Prerequisite: [#44](https://github.com/ControlSystemStudio/maven-osgi-bundles/pull/44)
Added SVG support to Display Builder through the [JavaFxSVG](https://github.com/codecentric/javafxsvg) library, providing a [custom image renderer to JavaFX 8](https://blog.codecentric.de/en/2015/03/adding-custom-image-renderer-javafx-8/) supporting SVG images.

Added SVG support.

---

org.csstudio.display.builder.model/examples/color.def
org.csstudio.display.builder.model/examples/font.def
org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/persist/NamedWidgetColors.java
org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/persist/NamedWidgetFonts.java

Allows font names to be used in font.def to define other font names.
So, now the following is possible:
```
Default      = Liberation Sans - regular - 14
Default Bold = Liberation Sans - bold    - 14
Header 1     = @Default Bold
```
Updated also the color.def file to match the new parsing mechanism.

CSSTUDIO-362 font.def

---

org.csstudio.javafx/src/org/csstudio/javafx/ClearingTextField.java

Hello @kasemir 
I like a lot your implementation: the clear button is much better than the other.
I just did a small change, increasing the linewidth to 1.7, using an old icon-design trick of never use 1 px wide line to represent meaningful information, but something more. Really on one of the monitors I've tested it the cross was barely visible (laptop retina display using full resolution).
Anyway, thank you for the implementation.

Increased the width of the cross inside the clear button.

---

org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/properties/ScriptInfo.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/ActionsDialog.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/ScriptsDialog.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/ActionButtonRepresentation.java

Without this change, when you press a transparent button it became opaque blue, i.e. the focus color cover the entire button because the background color is transparent.
Setting the alpha component of the focus color to 0.1, the focused button become partially transparent, showing what is placed under it.
The rgb components of `rgba(3,158,211,0.1)` correspond to `#039ED3`, the original value for `-fx-focus-color`.

Focus color for transparent buttons now has alpha set to 0.1.

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/LineNumberCellFactory.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/ScriptsDialog.java

- Removed the possibility to sort columns in PVs table, in order to keep the natural order used to refer to them.
- PVs Table's trigger column mad not resizable.
- Removed saving/restoring the size of the PVs Table's name column width.
- Added SplitPane as main container. Split divider position is saved/restored.
- Left-aligned buttons content.
- Added row numbers to PVs Table. This should make easier to identify the index of the PV to be used in scripts.

#286 dialogs issues: more enhancements in Scripts dialog.

---

org.csstudio.display.builder.feature/feature.xml
org.csstudio.display.builder.representation.javafx/META-INF/MANIFEST.MF
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/BaseKnobRepresentation.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/KnobRepresentation.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/ThumbWheelRepresentation.java
repository/display_runtime.product

Removed dependency from org.csstudio.platform.libs.gauges, and added the se.europeanspallationsource... ones.
See [#56](https://github.com/ControlSystemStudio/maven-osgi-bundles/pull/56).
After merging this pull request, [#64](https://github.com/ControlSystemStudio/cs-studio-thirdparty/pull/64) can be merged too.

Removed dependency from org.csstudio.platform.libs.gauges

---

org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/RulesDialog.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/ModalityHack.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/ScriptsDialog.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/opibuilder.css

Started reworking the Rules dialog.
@kasemir 
I've hugely simplified the ModalityHack class, removing the scheduled task in favour of the simpler `((Stage) window).setAlwaysOnTop(true)`. The advantages are that instead of having dialogs popping up here and there, they just stay on top of everything.
I've tested it on MacOS X and our CentOS 7.3 linux reference machine, and to me it seems working well (and it seems satisfy my stakeholders). Can you please test it and check if this change is OK for you too?

Issue #286: rules dialog

---

org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/PropertyPanelSection.java

If the combo box is not editable, then it only requests focus. This manner using the UP/DOWN arrow keys will be possible to select the previous/following item in the combo box.

On getting focus, editable combo boxes will select the existing text

---

org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/SymbolWidget.java
org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/TextSymbolWidget.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SymbolRepresentation.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/TextSymbolRepresentation.java

@kasemir 
I was asked to add rotation to symbol and text symbol widgets.
Text symbol widget rotation was made copying the label one.
I received complains about the rotation of the Picture widget, because the size of the actual rotated picture cannot be defined (unless inverting the roto-scale matrix used internally). To be honest, I don't like too the current picture rotation implementation, being not so intuitive. For this reason, I switched to the simplest implementation (JavaFX rotate) because in this way the width and height of the widget are also the ones of the image, then rotation is applied (this was the requirements from my stakeholders).

CSSTUDIO-558: Added rotation to Symbol and TextSymbol widgets.

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/AutocompleteMenu.java

It seems to me this can be the only possible source of the problem, now wrapped into a Platform.runLater call.
The exception was thrown at org.csstudio.display.builder.representation.javafx.AutocompleteMenu.lambda$1(AutocompleteMenu.java:279).
Difficult to reproduce: I had some randomly (on macOS X), some of my colleagues have the problem more often (on Linux VM).

CSSTUDIO-579: ConcurrentModificationException modifying PV names in Rules and/or Scripts dialog.

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/JFXUtil.java

Regular fonts not loaded correctly. See the attached picture before the change (left) and after (right), and the corresponding font definition file.
[fonts.def.zip](https://github.com/kasemir/org.csstudio.display.builder/files/1739335/fonts.def.zip)

Fixed font loading problem.

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/opibuilder.css

Fixed asymmetry in button's text.

---

org.csstudio.display.builder.feature/feature.xml
org.csstudio.javafx/META-INF/MANIFEST.MF

JavaFxSVG ver. 1.3.0 introduced a mechanism to load images in their original size, not the default 400x400 of ver. 1.2.1.
This new version cannot be used because of Eclipse clashing when loading batik SVG DOM factory (JavaFxSVG requires batik 1.8, but somewhere else in maven-osgi-bundles batik 1.7 is used).
For this reason, I made explicit the version needed by Display Builder (1.2.1), until a fix in maven-osgi-bundles is performed.

SVG image loading

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/ComboRepresentation.java

Combo box is not retriggering a PV write if the same element is (re)selected. This commit patches the behaviour.
@kasemir Do you think a specific property must be added to the Combo Widget, or can we have it as default behaviour?

CSSTUDIO-636: Combo box not retriggering PV write

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/BaseGaugeRepresentation.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/BaseKnobRepresentation.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SpinnerRepresentation.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/ThumbWheelRepresentation.java

- Added code to Spinner widget dealing with limits_from_pv.
- Fixed error conditions checking in Knob, Thumb Wheel and Meter/Gauge widgets.

CSSTUDIO-618: limits from PV not working in Spinner.

---

org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/actions/CreateGroupAction.java
org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/properties/InsetsWidgetProperty.java
org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/GroupWidget.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/GroupRepresentation.java

Updated the way groups handle the style change: basically when a group has no children, then it  doesn't resize when the style changes. Instead, when there are children the group is resized and repositioned to maintain the children at their user's perceived location.
To obtain that result, the following changes were made:
- when a group is created around some selected widgets, its initial style is now NONE and transparent (this is similar to what done by programs like KeyNote, PowerPoint, OmniGraffle, Visio, Illustrator, etc.). This is necessary because a predictable insets its needed independently of the default font used for the title;
- when the style is NONE, the special sub-pixel, dashed border is always drawn in editor mode (see picture);
- when visible, the title has a pad around …

CSSTUDIO-588: changing group style

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SymbolRepresentation.java

Forgot to request a `valueChange(...)` after all images are loaded, updating a previously value possibly clamped the the list size at that moment.

CSSTUDIO-637: Symbol widget showing wrong picture on (re-)load.

---

org.csstudio.display.builder.feature/feature.xml
org.csstudio.javafx/META-INF/MANIFEST.MF
org.csstudio.javafx/src/org/csstudio/javafx/Activator.java
pom.xml
repository/display_runtime.product

- Removed batik-related dependencies (SVG no more handled by batik and javafxsvg) because of an exception trying to load at Display startup of a `com.sun.xxx` library.
**Note:** it is better to perform this merge after #372, so that OPIs using SVG will still work using the new implementation provided by that pull request.

Updated to Eclipse 4.7 Oxygen.

---

org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/RulesDialog.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/ScriptsDialog.java

It works on Eclipse 4.7 Oxygen inside the [ESS product](https://github.com/ControlSystemStudio/org.csstudio.ess.product).

Restoring syntax highlight

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/PictureRepresentation.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SymbolRepresentation.java

SVG are represented as a Group node. Their preferred width and height is fixed (the size of the content) and cannot be changed. This creates a problem when rescaling to a size lower than the preferred one.
Using translation this solve the problem only when rotation is 0 (current fix, making ESS integrators happy for now).
To solve the problem completely I need more time and I want to think about having SVG loaded as Containers, or adding to SVGContent a methods that set the preferred size, performing the rescaling accordingly.

CSSTUDIO-691: SVG displayed outside bounds.

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/JFXStageRepresentation.java

My integrators lament the fact that when an action opens a DB OPI it can be covered by the main application window, and then lost forever.
I've fixed it setting the stage always on top, working on MacOS X and Linux (CentOS 7.4).
I've also prepared a more complex solution, having an "Always On Top" check box enabled when "Standalone" is selected on Actions dialog. But I don't know if it is really worth the changes (in many files).

CSSTUDIO-658: Stage set always on top.

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/JFXStageRepresentation.java

In a multi-screen situation, standalone window always open at (0,0), or at the location set in the Display widget itself, and this is annoying, requiring to do wide mouse movements to get the open window and move it on a reasonable position.
The change I've made save the location on close, and use it the next time the window is opened again.

Location saved and restored from preferences.

---

org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/DisplayEditor.java

Executing selection.clean() in the UI thread after the display model was set.

CSSTUDIO-625: On opening, properties of the DisplayModel are not displayed.

---

org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/PropertyPanelSection.java
org.csstudio.javafx/src/org/csstudio/javafx/InputUtils.java

This seems to be an Eclipse-RCP-related problem: while a pure JavaFX application treats RETURN and ENTER (numpad) keys identically, when JavaFX is embedded in Eclipse-RCP, ENTER doesn't work.
This has become a daily request by integrators at ESS, that use the numpad keyboard to enter values (positions, size, ...) and then press ENTER to validate them.
I've found what I think an elegant solution. I think I've wrapped all properties fields requiring RETURN to validate them. If not, as soon as someone will report it, it will be easy to fix.

CSSTUDIO-590 ENTER not validating properties

---

org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/tree/WidgetTree.java
org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/tree/WidgetTreeCell.java

When a clean-up of the designed OPI is needed, changing the names of the widgets from the Properties view is annoying and time-consuming.
The Overview/Widgets view now allows name edit by double-clicking the widget in the tree.

CSSTUDIO-624: in-place edit of widget's name in Overview/Widgets view

---

org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/util/GeometryTools.java

There is a problem in the previous implementation of lasso selection: if a group is selected, then the group AND its content is selected. If you then move the selection, everything seems going crazy, because the same offset is applied to the group and the its content, which has a different coordinate system. Even worse, because of #403 you cannot undo the operation.
In this PR, children are selected only if their container is not selected. So lassoing around a group select only the group, lassoing around its content only (starting from outside) will select the content.
My integrators raising the problem, tested and like it. Moreover, with CTRL/CMD (see #402) you can easily add to the selection something from the contents if needed.

CSSTUDIO-736: lasso selection

---

org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/DisplayEditor.java
org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/poly/PointsEditor.java
org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/tracker/SelectedWidgetUITracker.java
org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/util/Rubberband.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/JFXRepresentation.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/JFXBaseRepresentation.java

Zoom, extending selection with click or rubberbanding, adding points to polyline now working with COMMAND instead of CTRL on MacOS.

CSSTUDIO-739: CTRL+click operations problematic on MacOS

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/opibuilder.css

The previous 3D border contributed to the colour desaturation produced by the LED bulb shading. At the same time, the 2 pixels thick etched border was more distinguishable than the flat border at the same thickness. For this reason I've increased the thickness  of a it more than half pixel.
Before:
After:

Improved LED border visibility.

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SymbolRepresentation.java

- Proper handling of RUNTIME_VALUE_NO_PV.
- Updated improper setting of a JFX property.

RUNTIME_VALUE_NO_PV not properly handled in symbol widget

---

org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/util/WidgetTransfer.java
org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/SymbolWidget.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SymbolRepresentation.java

- Symbols property was not properly initialised.
- Fixed also symbol not updated if corresponding file was changed.
- A bit of refactoring.

CSSTUDIO-785 Single-image Symbol widget doesn't save the image file id create via ALD+D&D.

---

databrowser3/databrowser-plugins/org.csstudio.trends.databrowser3/src/org/csstudio/trends/databrowser3/Activator.java

Added try-catch block to catch an NPE blocking DataBrowser AND DisplayBuilder widgets to be loaded.
@kasemir 
All my last 3 PR are important to ESS, but this one is really blocking.
The `for (Monitor monitor : Display.getCurrent().getMonitors())` is generating the NPE that, no only prevents the DataBrowser plugin to be loaded, but then also the Display Builder to load widgets.
Is it possible that the DataBrowser plugin is activated before `Display.getCurrent()` has a valid value?

Catching an NPE blocking DataBrowser AND DisplayBuilder to start.

---

org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/BaseLEDWidget.java
org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/LEDWidget.java
org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/MultiStateLEDWidget.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/BaseLEDRepresentation.java

This was a pressing request from ESS integrators, because BOY had 'bulb_border_color', and during the conversion it is lost.

Added line_color to LED and MultiStateLED.

---

org.csstudio.display.builder.runtime.test/pom.xml
org.csstudio.display.builder.runtime.test/src/org/csstudio/display/builder/runtime/test/RuntimeTestsSuite.java

This PR closes #448.
Note that for CS-Studio the following was added to the `pom.xml`
```xml
<build>
<plugins>
<plugin>
<groupId>org.eclipse.tycho</groupId>
<artifactId>tycho-surefire-plugin</artifactId>
<version>1.1.0</version>
<configuration>
<testClass>org.csstudio.display.builder.runtime.test.RuntimeTestsSuite</testClass>
</configuration>
</plugin>
</plugins>
</build>
```
For Phoebus the following should be added instead:
```xml
<build>
<plugins>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-surefire-plugin</artifactId>
<version>2.22.0</version>
<configuration>
<includes>
<include>**/*Suite.java</include>
</includes>
</configuration>
</plugin>
</plugins>
</build>
```

Added test suite to execute tests in the right order.

---

org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/SymbolWidget.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/PictureRepresentation.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SymbolRepresentation.java
org.csstudio.javafx/META-INF/MANIFEST.MF
org.csstudio.javafx/src/org/csstudio/javafx/ImageCache.java

Symbol widget code was in time upgraded to add support for SVG and other features (mostly to loading images in multi-thread). This created a code wit some random problems loading problems and weird display of SVG image.
I've rewritten completely the code, now being more reliable and much faster. All SVG problems disappeared too (now SVGs a transformed into Images through the Node.snapshot(...) method).
I've update also the Picture widget for the SVG related code.
This patch closes 6 tickets at ESS regarding symbols loading and badly displayed SVGs.

CSSTUDIO-836 symbol widget

---

org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/ByteMonitorWidget.java

Importing is ByteMonitor with labels doesn't work as expected. Here the BOY example:
and here the imported one:
This is the situation after the fix:

Fixed wrong position of labels and missing foreground.

---

org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/CheckBoxWidget.java
org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/widgets/plots/ImageWidget.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/CheckBoxRepresentation.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/plots/ImageRepresentation.java
org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/RTImagePlot.java
org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/ImagePlot.java

CheckBox and Image widgets always drawn text in black, and when the background is dark it is difficult if not impossible to read. This PR fixes it.
@kasemir 
I've put a comment for you starting with `// CR:` because I'm not sure if the following statement is needed or not.

Added "foreground" property to CheckBox and Image.

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/PictureRepresentation.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SymbolRepresentation.java
org.csstudio.javafx/src/org/csstudio/javafx/ImageCache.java

Picture and Symbol widgets use an image cache to speed up (re)loading of OPI using the same image.
In edit mode, if you assign an image to a Picture widget and then update the image itself, reloading the OPI doesn't work because the Picture widget is now using the cached image.
I've fixed this problem removing the images from the cache when loading a Picture and Symbol widgets.

Don't use image cache in edit mode.

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/opibuilder.css
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/EmbeddedDisplayRepresentation.java

Using the Modena CSS `edge-to-edge` style for ScrollPane instead of `embedded_display`, and removed the extra pixels in width and height when resized.
See https://stackoverflow.com/a/29376445

Removing the 1px border around EmbeddedDisplay's content .

---

org.csstudio.javafx.rtplot/src/org/csstudio/javafx/rtplot/internal/ToolbarHandler.java

The PAN mode changes the min and max of vertical axes, possibly disrupting a carefully set ones. For this reason I was asked to have the POINTER mode set as default.
I did it in a straight way. I don't know if you @kasemir prefer to have a preference instead.

Default to POINTER in DataBrowser

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/BaseLEDRepresentation.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/BoolButtonRepresentation.java
org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/ByteMonitorRepresentation.java

I was reported that in the last version of Display Builder LED and MultiLED widgets always shows the Magenta (invalid/unconnected) colour in edit mode, instead of the OFF/State-0 one. In runtime mode, instead, everything was fine.
The fix was easy (`BaseLEDRepresentation:173`). I've improved (I think at least) how LEDs (LED, MultiLed, BoolButton and ByteMonitor) are displayed in edit mode, showing all the colours:
Here and example of what a synoptic view looks like in edit mode after the change:

LED colour alway magenta in editor mode

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/SpinnerRepresentation.java

In this way both the JavaFX (below) and the SWT context menus are displayed when right-clicking on the spinner's text area.
Pressing ESC will close the SWT menu. Pressing ESC again will close the JavaFX one.
I's a compromise I know, but that way we solve the problem, at least until we'll move to Phoebus.

Context menu triggering event forwarded to parent for Spinner widget when right-clicked in the text area.

---

databrowser3/databrowser-plugins/org.csstudio.trends.databrowser3/preferences.ini
databrowser3/databrowser-plugins/org.csstudio.trends.databrowser3/src/org/csstudio/trends/databrowser3/model/PVItem.java
databrowser3/databrowser-plugins/org.csstudio.trends.databrowser3/src/org/csstudio/trends/databrowser3/preferences/Preferences.java

I was requested to set the request type default value of a newly added trace to RAW instead of OPTIMIZED. I've added the preference into the ini file and the logic for it. I've set OPTIMIZED as default value in the ini file as it was originally in the code.

Added "request_type" preference to set the default request type in Data Browser.

---

org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/actions/ActionDescription.java

- The selection, any kind of, made with any of the possible ways, defines a bounding box.
- TOP will align the top border of all widgets with the top border of the bounding box.
- BOTTOM will align the bottom border of all widgets with the bottom border of the bounding box;
- MIDDLE will align the center of all widgets with the center of the of the bounding box;
- Similarly for LEFT, RIGHT and CENTER.

Updated alignment behaviour

---

org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/actions/ActionDescription.java

Widgets are geometrically ordered. If the sum of the widgets' size is less than the selection bounding box size, then widgets are "equal gap" distributed, otherwise their centers are equally distributed. In both cases the two extreme widgets maintain their location.

Distribution now operates on widget's position rather than selection order.

---

org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/DisplayEditorPart.java
org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/EditEmbeddedDisplayAction.java
org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/Messages.java
org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/OutlinePage.java
org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/actions/CopyAction.java
org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/actions/CutDeleteAction.java
org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/actions/PasteAction.java
org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/actions/RedoAction.java
org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/actions/UndoAction.java
org.csstudio.display.builder.editor.rcp/src/org/csstudio/display/builder/editor/rcp/messages.properties
org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/tree/WidgetTree.java

I've made the 2 contextual menu more similar to each other. Moreover no elements disappears/appears: instead their enabled status is changed.

Contextual menus restructured.

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/LabelRepresentation.java

Without this patch, a label whose text is set to be centered and wrapped will not center wrapped text.
The same happens if horizontally right-aligned.

Added missing text alignment.

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/BoolButtonRepresentation.java

Fix for the following problem:

Fixed LED of BoolButton initially drawn off-button if state-0 text is empty

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/EmbeddedDisplayRepresentation.java

In Edit mode, transparent Embedded displays with "No Resize" setting show unnecessary scrollbars when sized to the same size of the embedded content and the embedded OPI has its own content "touching" the boundaries.
This happens because in Edit mode a 1 pixel semi-transparent grey border is displayed inside the Embedded Display to identify the widget.
This PR replaces the this border with a transparent pattern background:

CSSTUDIO-1026: Transparent Embedded Background

---

org.csstudio.display.builder.representation.javafx/META-INF/MANIFEST.MF

Related to [maven-osgi-bundles#84](https://github.com/ControlSystemStudio/maven-osgi-bundles/pull/84).
This PR will remove to needs to update this version number each time `maven-osgi-bundles` is updated.

CSSTUDIO-949: Removing dependency version for ControlsFX

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/BaseGaugeRepresentation.java

Meters and gauges have some controls outside the Gauge control boundaries. Nevertheless those are invisible, they contribute to the selection area of the widget, allowing to select the widget far aside its boundaries.
A clipping rectangle was used around the Gauge object, a little bit larger to include the alarm borders.

CSSTUDIO-239: meters and gauges need to be clipped.

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/JFXBaseRepresentation.java

Sometimes when an OPI is closed the following shows up in the console (but not in the logs):
```
2019-06-12 17:27:57.820 WARNING [Thread 1] org.csstudio.display.builder.representation.javafx.JFXRepresentation (shutdown) - Display representation still contains items on shutdown
2019-06-12 17:30:01.302 WARNING [Thread 1] org.csstudio.display.builder.representation.javafx.JFXRepresentation (shutdown) - Display representation still contains items on shutdown
2019-06-12 18:37:44.649 WARNING [Thread 1] org.csstudio.display.builder.representation.javafx.JFXRepresentation (shutdown) - Display representation still contains items on shutdown
2019-06-12 18:41:25.397 WARNING [Thread 1] org.csstudio.display.builder.representation.javafx.JFXRepresentation (shutdown) - Display representation still …
```

Suppressed IllegalArgumentException when parent is null.

---

org.csstudio.display.builder.representation.javafx/src/org/csstudio/display/builder/representation/javafx/widgets/EmbeddedDisplayRepresentation.java

It seems related to ScrollPane having a minimum size of something around 36x36. Forcing it to 1x1 will solve the problem.

Fix for border in small embedded display never going smaller than 36x36.

---

org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/properties/PropertyPanelSection.java
org.csstudio.javafx/src/org/csstudio/javafx/InputUtils.java

I have complains about TextField-based properties
- not being easily visible the one where the caret is inside,
- not being easily visible if the ENTER key was pressed or not,
- not being easily usable because when click inside the content is not selected, 
- TAB navigation automatically select the content but not for editable combo boxes.
This PR addresses the problems in the following way:
- focused (and not yet modified) TextFields have a yellowish background and the content is initially selected;
- as soon as a new content is typed, the background change to reddish until ENTER is pressed, where is switched back to the yellowish one.

TextField properties highlighted.

---

org.csstudio.display.builder.editor/src/org/csstudio/display/builder/editor/undo/RemoveWidgetsAction.java

Phoebus [#729](https://github.com/shroffk/phoebus/pull/729)
The changes in RemoveWidgetAction are a step forward in solving UNDO/REDO issues. Still one remains: if a widget is moved outside a group, UNDO place is back in the group but not at the previous tree position.

Imported changes from Phoebus.
